### ISSUE TITLE
How to get the confusion matrix of the trained model ? 

### ISSUE THREAD

**Issue by rathnasubramanian2603** [thooun/tfx-sandbox#1]
I have a trained model..! I give it to the Model Evaluator component of TFX pipeline. How to extract the confusion Matrix from it ? If there are any sample Python Code to get the confusion matrix of a TFX trained model it would help me to understand it a lot. Thanks.

**Comment by thooun** [comment]
Hi,

In Kubeflow there is the concept of [Output viewer](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/) in order to do that but it's not yet available in TFX.

I'll write an example with Kubeflow using this kind of thing.
I'll notify you when I'll push it ;)
